# Generated by Django 6.0.2 on 2026-02-11 04:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_bagmodel_unique_together'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoritesmodel',
            unique_together={('user', 'product')},
        ),
    ]
