# Generated by Django 6.0.2 on 2026-02-18 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_favoritesmodel_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bagmodel',
            options={'ordering': ['id']},
        ),
    ]
