# Generated by Django 6.0.2 on 2026-02-09 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.PositiveBigIntegerField()),
                ('delivery', models.PositiveIntegerField()),
                ('total', models.PositiveBigIntegerField()),
                ('paymentmethod', models.CharField(choices=[('COD', 'CASH ON DELIVERY'), ('DEBIT CARD', 'DEBIT CARD'), ('CREDIT CARD', 'CREDIT CARD')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('DELIVERED', 'DELIVERED'), ('SHIPPED', 'SHIPPED'), ('OUT OF DELIVERY', 'OUT OF DELIVERY')], max_length=25)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.addressmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.PositiveBigIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productsmodel')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.ordersmodel')),
            ],
        ),
    ]
