# Generated by Django 6.0.2 on 2026-02-11 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitemsmodel_order'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitemsmodel',
            unique_together={('order', 'product')},
        ),
    ]
