# Generated by Django 6.0.2 on 2026-02-11 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitemsmodel_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitemsmodel',
            old_name='price',
            new_name='order_time_price',
        ),
    ]
