# Generated by Django 6.0.2 on 2026-02-14 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_price_orderitemsmodel_order_time_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemsmodel',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordereditems', to='orders.ordersmodel'),
        ),
        migrations.AlterField(
            model_name='ordersmodel',
            name='paymentmethod',
            field=models.CharField(choices=[('COD', 'CASH ON DELIVERY'), ('ONLINE', 'ONLINE PAYMENT')], max_length=20),
        ),
    ]
