# Generated by Django 6.0.2 on 2026-02-18 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_ordersmodel_created_at_alter_orderitemsmodel_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersmodel',
            name='paymentmethod',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ordersmodel',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('DELIVERED', 'DELIVERED'), ('SHIPPED', 'SHIPPED'), ('OUT OF DELIVERY', 'OUT OF DELIVERY'), ('CANCELLED', 'CANCELLED')], max_length=25),
        ),
    ]
