# Generated by Django 6.0.2 on 2026-02-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(max_length=20, null=True)),
                ('season', models.CharField(choices=[('WINTER', 'WINTER'), ('SUMMER', 'SUMMER'), ('RAINY', 'RAINY')], max_length=15)),
                ('price', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
            ],
        ),
    ]
