# Generated by Django 6.0.2 on 2026-02-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsmodel',
            name='image',
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
